/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated.payments'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated.tickets.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated.messages.index'
import { Route as AuthenticatedTicketsNewRouteImport } from './routes/_authenticated.tickets.new'
import { Route as AuthenticatedTicketsIdRouteImport } from './routes/_authenticated.tickets.$id'
import { Route as AuthenticatedMessagesTenantIdRouteImport } from './routes/_authenticated.messages.$tenantId'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated.admin.tickets'
import { Route as AuthenticatedAdminRentRouteImport } from './routes/_authenticated.admin.rent'
import { Route as AuthenticatedAdminAreasRouteImport } from './routes/_authenticated.admin.areas'
import { Route as AuthenticatedAdminTenantsIndexRouteImport } from './routes/_authenticated.admin.tenants.index'
import { Route as AuthenticatedAdminTenantsIdRouteImport } from './routes/_authenticated.admin.tenants.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsNewRoute = AuthenticatedTicketsNewRouteImport.update({
  id: '/tickets/new',
  path: '/tickets/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsIdRoute = AuthenticatedTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesTenantIdRoute =
  AuthenticatedMessagesTenantIdRouteImport.update({
    id: '/messages/$tenantId',
    path: '/messages/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRentRoute = AuthenticatedAdminRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAreasRoute = AuthenticatedAdminAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTenantsIndexRoute =
  AuthenticatedAdminTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTenantsIdRoute =
  AuthenticatedAdminTenantsIdRouteImport.update({
    id: '/tenants/$id',
    path: '/tenants/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/rent': typeof AuthenticatedAdminRentRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/messages/$tenantId': typeof AuthenticatedMessagesTenantIdRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/admin/tenants/$id': typeof AuthenticatedAdminTenantsIdRoute
  '/admin/tenants/': typeof AuthenticatedAdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/rent': typeof AuthenticatedAdminRentRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/messages/$tenantId': typeof AuthenticatedMessagesTenantIdRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/admin/tenants/$id': typeof AuthenticatedAdminTenantsIdRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/_authenticated/admin/rent': typeof AuthenticatedAdminRentRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/messages/$tenantId': typeof AuthenticatedMessagesTenantIdRoute
  '/_authenticated/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/_authenticated/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/admin/tenants/$id': typeof AuthenticatedAdminTenantsIdRoute
  '/_authenticated/admin/tenants/': typeof AuthenticatedAdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/documents'
    | '/payments'
    | '/profile'
    | '/admin/areas'
    | '/admin/rent'
    | '/admin/tickets'
    | '/messages/$tenantId'
    | '/tickets/$id'
    | '/tickets/new'
    | '/messages/'
    | '/tickets/'
    | '/admin/tenants/$id'
    | '/admin/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/documents'
    | '/payments'
    | '/profile'
    | '/admin/areas'
    | '/admin/rent'
    | '/admin/tickets'
    | '/messages/$tenantId'
    | '/tickets/$id'
    | '/tickets/new'
    | '/messages'
    | '/tickets'
    | '/admin/tenants/$id'
    | '/admin/tenants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/admin/areas'
    | '/_authenticated/admin/rent'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/messages/$tenantId'
    | '/_authenticated/tickets/$id'
    | '/_authenticated/tickets/new'
    | '/_authenticated/messages/'
    | '/_authenticated/tickets/'
    | '/_authenticated/admin/tenants/$id'
    | '/_authenticated/admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/new': {
      id: '/_authenticated/tickets/new'
      path: '/tickets/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof AuthenticatedTicketsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/$id': {
      id: '/_authenticated/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AuthenticatedTicketsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/$tenantId': {
      id: '/_authenticated/messages/$tenantId'
      path: '/messages/$tenantId'
      fullPath: '/messages/$tenantId'
      preLoaderRoute: typeof AuthenticatedMessagesTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rent': {
      id: '/_authenticated/admin/rent'
      path: '/rent'
      fullPath: '/admin/rent'
      preLoaderRoute: typeof AuthenticatedAdminRentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/areas': {
      id: '/_authenticated/admin/areas'
      path: '/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AuthenticatedAdminAreasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenants/': {
      id: '/_authenticated/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AuthenticatedAdminTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenants/$id': {
      id: '/_authenticated/admin/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AuthenticatedAdminTenantsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAreasRoute: typeof AuthenticatedAdminAreasRoute
  AuthenticatedAdminRentRoute: typeof AuthenticatedAdminRentRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminTenantsIdRoute: typeof AuthenticatedAdminTenantsIdRoute
  AuthenticatedAdminTenantsIndexRoute: typeof AuthenticatedAdminTenantsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAreasRoute: AuthenticatedAdminAreasRoute,
  AuthenticatedAdminRentRoute: AuthenticatedAdminRentRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminTenantsIdRoute: AuthenticatedAdminTenantsIdRoute,
  AuthenticatedAdminTenantsIndexRoute: AuthenticatedAdminTenantsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMessagesTenantIdRoute: typeof AuthenticatedMessagesTenantIdRoute
  AuthenticatedTicketsIdRoute: typeof AuthenticatedTicketsIdRoute
  AuthenticatedTicketsNewRoute: typeof AuthenticatedTicketsNewRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMessagesTenantIdRoute: AuthenticatedMessagesTenantIdRoute,
  AuthenticatedTicketsIdRoute: AuthenticatedTicketsIdRoute,
  AuthenticatedTicketsNewRoute: AuthenticatedTicketsNewRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
